
const constants = {
	CATS_VIEWED: 'CATS_VIEWED',
	CATS_REQUESTED: 'CATS_REQUESTED',
	CATS_FETCHED: 'CATS_FETCHED',
	CATS_FAILED: 'CATS_FAILED',
	DOGS_VIEWED: 'DOGS_VIEWED',
	DOGS_REQUESTED: 'DOGS_REQUESTED',
	DOGS_FETCHED: 'DOGS_FETCHED',
	DOGS_FAILED: 'DOGS_FAILED',
	SNAKES_VIEWED: 'SNAKES_VIEWED',
	SNAKES_REQUESTED: 'SNAKES_REQUESTED',
	SNAKES_FETCHED: 'SNAKES_FETCHED',
	SNAKES_FAILED: 'SNAKES_FAILED',
}

export default constants
